### ISSUE TITLE
Does not support paginated responses

### ISSUE THREAD

**Issue by stephenjlevy** [CenturyLinkLabs/fleet-api#11]
There doesn't seem to be support for the Fleet API's paginated response feature for large responses (See https://github.com/coreos/fleet/blob/master/Documentation/api-v1.md#pagination).

**Comment by bdehamer** [comment]
@stephenjlevy you are correct, there currently is no support for paginated responses. It's on my list of things to look at, but would welcome the help if you want to take a crack at it. Thanks.
