### ISSUE TITLE
Unit interactions are a struggle

### ISSUE THREAD

**Issue by shadoi** [CenturyLinkLabs/fleet-api#12]
Currently if I want to update a unit it requires bypassing the ServiceDefinition class entirely as it won't handle the additional required attributes, and the Fleet::Client::Update#update_unit method doesn't take a ServiceDefinition object.  So as it stands, it's necessary to handle both formats and convert between the two.

I propose either:
1. Getting rid of ServiceDefinition entirely and just operate on the fleet hash directly
2. make all methods currently in Fleet::Client::Unit move to ServiceDefinition, which would require probably a more significant refactor than the first option.

I'm happy to submit a PR if you agree with either of these, or have a better idea.

**Comment by bdehamer** [comment]
@shadoi can you help me understand the use-case a little more. I didn't anticipate that anyone would call update_unit directly since all of the state changes can be handled through `load`, `start`, `stop` and `unload` methods (which use `update_unit` internally). Let me know what you're trying to do with `update_unit` and we'll try and come up with a good solution.

Thanks.

**Comment by shadoi** [comment]
My main issues are with updating units, which I realized after creating this issue, isn't even possible right now with the HTTP API directly (https://github.com/coreos/fleet/issues/1266).  

I've reverted to just destroying and creating units to update them which avoids the problems I was having using update_unit.  If they actually change that limitation then it would be very convenient to be able to update the contents of a unit's hash without having to convert to/from the ServiceDefinition expectation that it look like { 'Unit' => {'description' => 'blah blah' ... } instead of the JSON structure that comes back from the fleet API directly.

**Comment by bdehamer** [comment]
Agreed. If they update the Fleet API to support updates to a unit (beyond just status changes) we'll definitely re-jigger the client to better support that.

It sounds like we're doing the same thing that you are right now. When we need to update a unit, we first destroy the old one and then submit the new one.
