### ISSUE TITLE
JSON vs Ruby Hash

### ISSUE THREAD

**Issue by ianblenke** [CenturyLinkLabs/fleet-api#2]
How do I define a unit for a multi-ExecStart service?

The Fleet API takes a tuplet like:

    "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]

This allows for duplicate "name" keys in a section, allowing me to do something like:

    "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]
                     {"section": "Service", "name": "ExecStart", "value": "/usr/bin/echo Done."}]

Unfortunately, the fleet-api service definition doesn't allow for this:

    {
      'Service' => {
        'ExecStart' => "/usr/bin/sleep 3000"
        'ExecStart' => "/usr/bin/echo Done."
      }
    }

Unlike a JSON object that does allow multiple "keys" as it is not an associative array, a ruby Hash _is_ an associative array... unless I'm missing something here? (which is entirely possible)

Thanks!

**Comment by brettnem** [comment]
I'd just like to say I was looking for this exact issue on the main page. You might want to make reference to this capability in the documentation.

Thanks!

**Comment by bdehamer** [comment]
Readme has been updated with instructions for multi-valued keys.
