### ISSUE TITLE
Get list of all units

### ISSUE THREAD

**Issue by brettnem** [CenturyLinkLabs/fleet-api#3]
Hello, 
Is there a way to get all units or all unit files?

Basically looking for the equiv of:
list-units
and
list-unit-files

This would give me something to iterate if I didn't already know the name of the units

**Comment by bdehamer** [comment]
@brettnem it's not mentioned in the README, but there is a `list_units` call that is available on the client.

**Comment by brettnem** [comment]
I actually did check out the list_units method. The problem with it is that it lists stale units (replaced by newer versions) and the returned object doesn't actually return the unit name; only hashes. 

 I made a command similar to what i'm looking for utilizing the etcd calls like this:
I first pull this: http://#{@endpoint_ip}/v2/keys/_coreos.com/fleet/state?consistent=true&recursive=true&sorted=true

Then I pull this:
http://#{@endpoint_ip}/v2/keys/_coreos.com/fleet/machines/#{machine_id}/object?consistent=true&recursive=true&sorted=true

And I combine that information into one returned hash where I can see what units are in what state and the machine it's on:
{"name"=>"test1.service", "state"=>"inactive", "machine_id"=>"xxxxxxxx", "machine_ip"=>"10.0.1.1"}

Of course I heavily truncated the output of both commands, but you can see what I'm trying to do. Basically, I'm looking for a way to get a snapshot of what's running and where. This is similar to what you get from the `fleetctl list-units` command.

Thanks!

**Comment by bdehamer** [comment]
@brettnem I added a new `list` method to the client that works like this:

```
irb(main):001:0> Fleet.new.list
=> [{:name=>"forever.service", :load_state=>"loaded", :active_state=>"active", :sub_state=>"running", :machine_id=>"262aed1f09954eff8157896d536686fa", :machine_ip=>"10.0.2.15"}]
```

Do you want to give that a spin and see if it works for you? You can find the code on this branch for now:
https://github.com/CenturyLinkLabs/fleet-api/pull/4

**Comment by brettnem** [comment]
Awesome, thanks. I'll give this a try today and I'll let you know how it goes!
