### ISSUE TITLE
Neither Fleet::Client#get_unit or Fleet::Client#status return active state

### ISSUE THREAD

**Issue by shadoi** [CenturyLinkLabs/fleet-api#8]
Means that the only way to see the actual state for a service is to parse the entire list of all launched units (which could be quite large in a big cluster).

Ideally an instance unit doesn't show up in the equivalent of "fleetctl list-unit-files", only in "fleetctl list-units".  

Maybe a distinction in the API client would provide more clarity, like #get_unit_file (current behavior for get_unit), and #get_unit would return only active units?

**Comment by bdehamer** [comment]
Added `get_unit_state` and `get_unit_file` methods in 1.0.0 release
