### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by stephenjlevy** [CenturyLinkLabs/fleet-api#9]
With the switch from faraday to excon, I'm now seeing a "Error loading unit file 757: unexpected token at '404 page not found" message when making load requests.

**Comment by bdehamer** [comment]
@stephenjlevy can you give me some more details about the context in which you are seeing the error:

* What is the service descriptor you're passing into the `load` calls?
* How are you connecting to the Fleet API endpoint? Are you manually configuring the endpoint with the `fleet_api_url` attribute? Setting the FLEETCTL_ENDPOINT environment variable? Relying on the default `unix://var/run/fleet.sock` URL?

**Comment by stephenjlevy** [comment]
I did not realize that you changed the API to use the fleet api directly.  I was still setting the etcd API as the endpoint.
